FROM base/ubuntu:latest

WORKDIR /root/

RUN wget https://github.com/digitalocean/doctl/releases/download/v1.54.0/doctl-1.54.0-linux-amd64.tar.gz

RUN tar xf /root/doctl-1.54.0-linux-amd64.tar.gz

RUN mv ~/doctl /usr/local/bin

RUN rm doctl-1.54.0-linux-amd64.tar.gz