FROM base/ubuntu:latest

LABEL type="base"

RUN apt update; apt install -y jq

RUN wget https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip

RUN unzip terraform_0.15.0_linux_amd64.zip

RUN rm terraform_0.15.0_linux_amd64.zip

RUN mv terraform /usr/bin/terraform
