FROM base/ubuntu:latest

LABEL type="base"

RUN wget https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip

RUN unzip terraform_0.14.5_linux_amd64.zip

RUN rm terraform_0.14.5_linux_amd64.zip

RUN mv terraform /usr/bin/terraform