FROM ubuntu:latest

LABEL type="base"

ENV TZ=Asia/Jakarta

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update

RUN apt upgrade -y

RUN apt install -y python3

RUN apt install -y wget

RUN apt install -y unzip